all : client.go
	@echo "------------------------------------------------------"
	@echo Building CAN client simulation
	@echo "------------------------------------------------------"	
	go build -o client client.go 

clean :
	rm -f client