test: 
	@echo "------------------------------------------------------"
	@echo Testing can.go (go wrapper over canlib.so)
	@echo "------------------------------------------------------"	
	go test can_test.go

clean:
	rm -f canlib.h libcan.so
