all : device.go
	@echo "------------------------------------------------------"
	@echo Building simulated device
	@echo "------------------------------------------------------"	
	go build -o device device.go 
	
clean :
	rm -f device