all : api.go
	@echo "------------------------------------------------------"
	@echo Building web client backend API
	@echo "------------------------------------------------------"	
	go build api.go

clean:
	rm -f api