all : api.go client.go
	@echo "------------------------------------------------------"
	@echo Building web client backend API
	@echo "------------------------------------------------------"	
	go build 

clean:
	rm -f api