name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5.0.0
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
          # go-version:
          # Path to the go.mod or go.work file.
          go-version-file: ./go.work
          # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
          # check-latest: true # optional
          # Used to pull Go distributions from go-versions.
          # Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
          # token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
          # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
          cache: false
          # Used to specify the path to a dependency file - go.sum
          cache-dependency-path: go.work.sum
          # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
          # architecture: # optional
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
      - run: make
